#pragma once

typedef enum
{
    INTERP_NEAREST,
    INTERP_LINEAR,
    INTERP_GLSL_LINEAR,
    INTERP_GLSL_BI_CUBIC_TRIANGULAR,
    INTERP_GLSL_BI_CUBIC_BELL,
    INTERP_GLSL_BI_CUBIC_B_SPLINE,
    INTERP_GLSL_BI_CUBIC_CATMULL,
}
INTERPOLATION_TYPE_e;
