#define  GL_FRAGMENT_PROGRAM_ARB 0x8B30
#define GL_VERTEX_PROGRAM_ARB 0x8B31
#define GL_OBJECT_COMPILE_STATUS_ARB             0x8B81
#ifndef GL_ARB_multitexture
#define GL_TEXTURE0		0x84C0
#define GL_TEXTURE1		0x84C1
#define GL_TEXTURE2		0x84C2
#define GL_TEXTURE3		0x84C3
#define GL_TEXTURE4		0x84C4
#define GL_TEXTURE5		0x84C5
#define GL_TEXTURE6		0x84C6
#define GL_TEXTURE7		0x84C7
#define GL_TEXTURE8		0x84C8
#define GL_TEXTURE9		0x84C9
#define GL_TEXTURE10	0x84CA
#define GL_TEXTURE11	0x84CB
#define GL_TEXTURE12	0x84CC
#define GL_TEXTURE13	0x84CD
#define GL_TEXTURE14	0x84CE
#define GL_TEXTURE15	0x84CF
#define GL_TEXTURE16	0x84D0
#define GL_TEXTURE17	0x84D1
#define GL_TEXTURE18	0x84D2
#define GL_TEXTURE19	0x84D3
#define GL_TEXTURE20	0x84D4
#define GL_TEXTURE21	0x84D5
#define GL_TEXTURE22	0x84D6
#define GL_TEXTURE23	0x84D7
#define GL_TEXTURE24	0x84D8
#define GL_TEXTURE25	0x84D9
#define GL_TEXTURE26	0x84DA
#define GL_TEXTURE27	0x84DB
#define GL_TEXTURE28	0x84DC
#define GL_TEXTURE29	0x84DD
#define GL_TEXTURE30	0x84DE
#define GL_TEXTURE31	0x84DF
#define GL_ACTIVE_TEXTURE             0x84E0
#define GL_CLIENT_ACTIVE_TEXTURE      0x84E1
#define GL_MAX_TEXTURE_UNITS          0x84E2
#define GL_TEXTURE0_ARB		GL_TEXTURE0	                
#define GL_TEXTURE1_ARB		GL_TEXTURE1	                
#define GL_TEXTURE2_ARB		GL_TEXTURE2	                
#define GL_TEXTURE3_ARB		GL_TEXTURE3	                
#define GL_TEXTURE4_ARB		GL_TEXTURE4	                
#define GL_TEXTURE5_ARB		GL_TEXTURE5	                
#define GL_TEXTURE6_ARB		GL_TEXTURE6	                
#define GL_TEXTURE7_ARB		GL_TEXTURE7	                
#define GL_TEXTURE8_ARB		GL_TEXTURE8	                
#define GL_TEXTURE9_ARB		GL_TEXTURE9	                
#define GL_TEXTURE10_ARB	GL_TEXTURE10                
#define GL_TEXTURE11_ARB	GL_TEXTURE11                
#define GL_TEXTURE12_ARB	GL_TEXTURE12                
#define GL_TEXTURE13_ARB	GL_TEXTURE13                
#define GL_TEXTURE14_ARB	GL_TEXTURE14                
#define GL_TEXTURE15_ARB	GL_TEXTURE15                
#define GL_TEXTURE16_ARB	GL_TEXTURE16                
#define GL_TEXTURE17_ARB	GL_TEXTURE17                
#define GL_TEXTURE18_ARB	GL_TEXTURE18                
#define GL_TEXTURE19_ARB	GL_TEXTURE19                
#define GL_TEXTURE20_ARB	GL_TEXTURE20                
#define GL_TEXTURE21_ARB	GL_TEXTURE21                
#define GL_TEXTURE22_ARB	GL_TEXTURE22                
#define GL_TEXTURE23_ARB	GL_TEXTURE23                
#define GL_TEXTURE24_ARB	GL_TEXTURE24                
#define GL_TEXTURE25_ARB	GL_TEXTURE25                
#define GL_TEXTURE26_ARB	GL_TEXTURE26                
#define GL_TEXTURE27_ARB	GL_TEXTURE27                
#define GL_TEXTURE28_ARB	GL_TEXTURE28                
#define GL_TEXTURE29_ARB	GL_TEXTURE29                
#define GL_TEXTURE30_ARB	GL_TEXTURE30                
#define GL_TEXTURE31_ARB	GL_TEXTURE31                
#define GL_ACTIVE_TEXTURE_ARB          GL_ACTIVE_TEXTURE
#define GL_CLIENT_ACTIVE_TEXTURE_ARB   GL_CLIENT_ACTIVE_TEXTURE
#define GL_MAX_TEXTURE_UNITS_ARB       GL_MAX_TEXTURE_UNITS
#endif